### ISSUE TITLE
CT Fatal error: spawn:

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/area-model-introduction#10]
```
area-model-introduction : build
Build failed with status code 3:
Running "default" task
Building runnable repository (area-model-introduction, brands: phet)
Building brand: phet
>> Webpack build complete: 6139ms
Fatal error: spawn: /data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/perennial-alias/node_modules/.bin/tsx "/data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/chipper/js/grunt/tasks/default.ts" "--brands=phet" "--noTranspile" "--lint=false" "--noTSC" failed with code 1

node:internal/process/promises:391
    triggerUncaughtException(err, true /* fromPromise */);
    ^

AssertionError [ERR_ASSERTION]: Missing string information for area-model-common a11y.partitionDescription
    at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/chipper/js/grunt/getStringMap.js:223:11
    at Array.forEach (<anonymous>)
    at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/chipper/js/grunt/getStringMap.js:211:15
    at Array.forEach (<anonymous>)
    at /data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/chipper/js/grunt/getStringMap.js:210:23
    at Array.forEach (<anonymous>)
    at getStringMap (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/chipper/js/grunt/getStringMap.js:147:24)
    at default (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/chipper/js/grunt/buildRunnable.ts:166:41)
    at async <anonymous> (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/chipper/js/grunt/tasks/build.ts:131:11)
    at async Object.startAsync (/data/share/phet/continuous-testing/ct-main/ct-snapshots/1731015458869/perennial-alias/js/common/phetTimingLog.js:133:20) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

Node.js v20.18.0
Snapshot from 11/7/2024, 2:37:38 PM
```

**Comment by jonathanolson** [comment]
Looks like this was caused from https://github.com/phetsims/area-model-common/commit/05664797093551c44fc207c676dc2d2343977409#diff-a339298d158ddbc1f7ec53a3857e27c2e0de882bd33303395f68568b558eaf35R165.

**Comment by jonathanolson** [comment]
Should be fixed with the above commit.
